name: westcardapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.1.1
  http: ^0.12.0+4
  cupertino_icons: ^0.1.2
  flutter_secure_storage: ^3.3.3
  crypto: ^2.1.3
  flushbar:
    git:
      url: git://github.com/valterh4ck3r/flushbar
      ref: master
  keyboard_visibility: ^0.5.6
  flutter_bloc: ^4.0.0
  qr_flutter: ^3.2.0
  barcode_scan: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/assets/main-icon.png
    - lib/assets/fondo_1.jpg
    - lib/assets/fondo_2.jpg
    - lib/assets/SplashScreen.png
    - lib/assets/freeCards/tarjeta_1/azul.png
    - lib/assets/freeCards/tarjeta_1/verde.png
    - lib/assets/freeCards/tarjeta_1/rojo.png
    - lib/assets/freeCards/tarjeta_2/azul.png
    - lib/assets/freeCards/tarjeta_2/verde.png
    - lib/assets/freeCards/tarjeta_2/rojo.png
    - lib/assets/freeCards/tarjeta_3/azul.png
    - lib/assets/freeCards/tarjeta_3/verde.png
    - lib/assets/freeCards/tarjeta_3/rojo.png
    - lib/assets/freeCards/tarjeta_4/azul.png
    - lib/assets/freeCards/tarjeta_4/verde.png
    - lib/assets/freeCards/tarjeta_4/rojo.png
    - lib/assets/freeCards/tarjeta_5/azul.png
    - lib/assets/freeCards/tarjeta_5/verde.png
    - lib/assets/freeCards/tarjeta_5/rojo.png
    - lib/assets/freeCards/tarjeta_6/azul.png
    - lib/assets/freeCards/tarjeta_6/verde.png
    - lib/assets/freeCards/tarjeta_6/rojo.png
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
