name: westcardapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.1.1
  flutter_bloc: ^3.2.0
  http: ^0.12.0+4
  connectivity: ^0.4.8+1
  cupertino_icons: ^0.1.2
  beauty_textfield: ^0.0.1
  flutter_secure_storage: ^3.3.1+1
  crypto: ^2.1.3
  flutter_svg: ^0.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - lib/assets/main-icon.png
    - lib/assets/SplashScreen.svg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
